# **Profit Preditction Using Multiple Regression Algorithm**

### Importing necessary libraries

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, r2_score , mean_absolute_error, mean_squared_error, root_mean_squared_error

In [22]:
df = pd.read_csv(r"D:\Machine_learning\supervised_learning\Datasets\online.csv")
df

    Marketing Spend  Administration  Transport     Area     Profit
0         114523.61       136897.80  471784.10    Dhaka  192261.83
1         162597.70       151377.59  443898.53      Ctg  191792.06
2         153441.51       101145.55  407934.54  Rangpur  191050.39
3         144372.41       118671.85  383199.62    Dhaka  182901.99
4         142107.34        91391.77  366168.42  Rangpur  166187.94
5         131876.90        99814.71  362861.36    Dhaka  156991.12
6         134615.46       147198.87  127716.82      Ctg  156122.51
7         130298.13       145530.06  323876.68  Rangpur  155752.60
8         120542.52       148718.95  311613.29    Dhaka  152211.77
9         123334.88       108679.17  304981.62      Ctg  149759.96
10        101913.08       110594.11  229160.95  Rangpur  146121.95
11        100671.96        91790.61  249744.55      Ctg  144259.40
12         93863.75       127320.38  249839.44  Rangpur  141585.52
13         91992.39       135495.07  252664.93      Ctg  134307.35
14        119943.24       156547.42  256512.92  Rangpur  132602.65
15        165349.20       122616.84  261776.23    Dhaka  129917.04
16         78013.11       121597.55  264346.06      Ctg  126992.93
17         94657.16       145077.58  282574.31    Dhaka  125370.37
18         91749.16       114175.79  294919.57  Rangpur  124266.90
19         86419.70       153514.11       0.00    Dhaka  122776.86
20         76253.86       113867.30  298664.47      Ctg  118474.03
21         78389.47       153773.43  299737.29    Dhaka  111313.02
22         73994.56       122782.75  303319.26  Rangpur  110352.25
23         67532.53       105751.03  304768.73  Rangpur  108733.99
24         77044.01        99281.34  140574.81    Dhaka  108552.04
25         64664.71       139553.16  137962.62      Ctg  107404.34
26         75328.87       144135.98  134050.07  Rangpur  105733.54
27         72107.60       127864.55  353183.81    Dhaka  105008.31
28         66051.52       182645.56  118148.20  Rangpur  103282.38
29         65605.48       153032.06  107138.38    Dhaka  101004.64
30         61994.48       115641.28   91131.24  Rangpur   99937.59
31         61136.38       152701.92   88218.23    Dhaka   97483.56
32         63408.86       129219.61   46085.25      Ctg   97427.84
33         55493.95       103057.49  214634.81  Rangpur   96778.92
34         46426.07       157693.92  210797.67      Ctg   96712.80
35         46014.02        85047.44  205517.64    Dhaka   96479.51
36         28663.76       127056.21  201126.82  Rangpur   90708.19
37         44069.95        51283.14  197029.42      Ctg   89949.14
38         20229.59        65947.93  185265.10    Dhaka   81229.06
39         38558.51        82982.09  174999.30      Ctg   81005.76
40         28754.33       118546.05  172795.67      Ctg   78239.91
41         27892.92        84710.77  164470.71  Rangpur   77798.83
42         23640.93        96189.63  148001.11      Ctg   71498.49
43         15505.73       127382.30   35534.17    Dhaka   69758.98
44         22177.74       154806.14   28334.72      Ctg   65200.33
45          1000.23       124153.04    1903.93    Dhaka   64926.08
46          1315.46       115816.21  297114.46  Rangpur   49490.75
47             0.00       135426.92       0.00      Ctg   42559.73
48           542.05        51743.15       0.00    Dhaka   35673.41
49             0.00       116983.80   45173.06      Ctg   14681.40

##  **Exploring the Dataset**

In [23]:
df.shape

(50, 5)

In [24]:
list(df.columns)

['Marketing Spend', 'Administration', 'Transport', 'Area', 'Profit']

In [25]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          0
Area               0
Profit             0
dtype: int64

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Marketing Spend  50 non-null     float64
 1   Administration   50 non-null     float64
 2   Transport        50 non-null     float64
 3   Area             50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

##  **Encoding the categorical column**

In [27]:
catecol = df.select_dtypes(exclude= 'number')
list(catecol)

['Area']

In [28]:
df = pd.get_dummies(data= df, columns= ['Area'], drop_first= True, dtype= int)
df

,Marketing Spend,Administration,Transport,Profit,Area_Dhaka,Area_Rangpur
0,114523.61,136897.80,471784.10,192261.83,1,0
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,0,1
3,144372.41,118671.85,383199.62,182901.99,1,0
4,142107.34,91391.77,366168.42,166187.94,0,1
5,131876.90,99814.71,362861.36,156991.12,1,0
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,0,1
8,120542.52,148718.95,311613.29,152211.77,1,0
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,0,1
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,0,1
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,0,1
15,165349.20,122616.84,261776.23,129917.04,1,0
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,1,0
18,91749.16,114175.79,294919.57,124266.90,0,1
19,86419.70,153514.11,0.00,122776.86,1,0
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,1,0
22,73994.56,122782.75,303319.26,110352.25,0,1
23,67532.53,105751.03,304768.73,108733.99,0,1
24,77044.01,99281.34,140574.81,108552.04,1,0
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,0,1
27,72107.60,127864.55,353183.81,105008.31,1,0
28,66051.52,182645.56,118148.20,103282.38,0,1
29,65605.48,153032.06,107138.38,101004.64,1,0
30,61994.48,115641.28,91131.24,99937.59,0,1
31,61136.38,152701.92,88218.23,97483.56,1,0
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,0,1
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,1,0
36,28663.76,127056.21,201126.82,90708.19,0,1
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,1,0
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,0,1
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,1,0
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,1,0
46,1315.46,115816.21,297114.46,49490.75,0,1
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,1,0
49,0.00,116983.80,45173.06,14681.40,0,0

## **Scaling the numerical columns**

In [29]:
numericalcols = df.select_dtypes(include= 'number')
list(numericalcols)

['Marketing Spend',
 'Administration',
 'Transport',
 'Profit',
 'Area_Dhaka',
 'Area_Rangpur']

In [30]:
scaler = StandardScaler()
scaledCols = scaler.fit_transform(df[['Marketing Spend','Administration','Transport']])

scaledCols

array([[ 8.97913123e-01,  5.60752915e-01,  2.15394309e+00],
       [ 1.95586034e+00,  1.08280658e+00,  1.92360040e+00],
       [ 1.75436374e+00, -7.28257028e-01,  1.62652767e+00],
       [ 1.55478369e+00, -9.63646307e-02,  1.42221024e+00],
       [ 1.50493720e+00, -1.07991935e+00,  1.28152771e+00],
       [ 1.27980001e+00, -7.76239071e-01,  1.25421046e+00],
       [ 1.34006641e+00,  9.32147208e-01, -6.88149930e-01],
       [ 1.24505666e+00,  8.71980011e-01,  9.32185978e-01],
       [ 1.03036886e+00,  9.86952101e-01,  8.30886909e-01],
       [ 1.09181921e+00, -4.56640246e-01,  7.76107440e-01],
       [ 6.20398248e-01, -3.87599089e-01,  1.49807267e-01],
       [ 5.93085418e-01, -1.06553960e+00,  3.19833623e-01],
       [ 4.43259872e-01,  2.15449064e-01,  3.20617441e-01],
       [ 4.02077603e-01,  5.10178953e-01,  3.43956788e-01],
       [ 1.01718075e+00,  1.26919939e+00,  3.75742273e-01],
       [ 2.01641149e+00,  4.58678535e-02,  4.19218702e-01],
       [ 9.44411957e-02,  9.11841968e-03,  4.40446224e-01],
       [ 4.60720127e-01,  8.55666318e-01,  5.91016724e-01],
       [ 3.96724938e-01, -2.58465367e-01,  6.92992062e-01],
       [ 2.79441650e-01,  1.15983657e+00, -1.74312698e+00],
       [ 5.57260867e-02, -2.69587651e-01,  7.23925995e-01],
       [ 1.02723599e-01,  1.16918609e+00,  7.32787791e-01],
       [ 6.00657792e-03,  5.18495648e-02,  7.62375876e-01],
       [-1.36200724e-01, -5.62211268e-01,  7.74348908e-01],
       [ 7.31146008e-02, -7.95469167e-01, -5.81939297e-01],
       [-1.99311688e-01,  6.56489139e-01, -6.03516725e-01],
       [ 3.53702028e-02,  8.21717916e-01, -6.35835495e-01],
       [-3.55189938e-02,  2.35068543e-01,  1.17427116e+00],
       [-1.68792717e-01,  2.21014050e+00, -7.67189437e-01],
       [-1.78608540e-01,  1.14245677e+00, -8.58133663e-01],
       [-2.58074369e-01, -2.05628659e-01, -9.90357166e-01],
       [-2.76958231e-01,  1.13055391e+00, -1.01441945e+00],
       [-2.26948675e-01,  2.83923813e-01, -1.36244978e+00],
       [-4.01128925e-01, -6.59324033e-01,  2.98172434e-02],
       [-6.00682122e-01,  1.31053525e+00, -1.87861793e-03],
       [-6.09749941e-01, -1.30865753e+00, -4.54931587e-02],
       [-9.91570153e-01,  2.05924691e-01, -8.17625734e-02],
       [-6.52532310e-01, -2.52599402e+00, -1.15608256e-01],
       [-1.17717755e+00, -1.99727037e+00, -2.12784866e-01],
       [-7.73820359e-01, -1.38312156e+00, -2.97583276e-01],
       [-9.89577015e-01, -1.00900218e-01, -3.15785883e-01],
       [-1.00853372e+00, -1.32079581e+00, -3.84552407e-01],
       [-1.10210556e+00, -9.06937535e-01, -5.20595959e-01],
       [-1.28113364e+00,  2.17681524e-01, -1.44960468e+00],
       [-1.13430539e+00,  1.20641936e+00, -1.50907418e+00],
       [-1.60035036e+00,  1.01253936e-01, -1.72739998e+00],
       [-1.59341322e+00, -1.99321741e-01,  7.11122474e-01],
       [-1.62236202e+00,  5.07721876e-01, -1.74312698e+00],
       [-1.61043334e+00, -2.50940884e+00, -1.74312698e+00],
       [-1.62236202e+00, -1.57225506e-01, -1.36998473e+00]])

In [31]:
scaled_df = pd.DataFrame(scaledCols, columns= ['Marketing Spend','Administration','Transport'])
scaled_df

    Marketing Spend  Administration  Transport
0          0.897913        0.560753   2.153943
1          1.955860        1.082807   1.923600
2          1.754364       -0.728257   1.626528
3          1.554784       -0.096365   1.422210
4          1.504937       -1.079919   1.281528
5          1.279800       -0.776239   1.254210
6          1.340066        0.932147  -0.688150
7          1.245057        0.871980   0.932186
8          1.030369        0.986952   0.830887
9          1.091819       -0.456640   0.776107
10         0.620398       -0.387599   0.149807
11         0.593085       -1.065540   0.319834
12         0.443260        0.215449   0.320617
13         0.402078        0.510179   0.343957
14         1.017181        1.269199   0.375742
15         2.016411        0.045868   0.419219
16         0.094441        0.009118   0.440446
17         0.460720        0.855666   0.591017
18         0.396725       -0.258465   0.692992
19         0.279442        1.159837  -1.743127
20         0.055726       -0.269588   0.723926
21         0.102724        1.169186   0.732788
22         0.006007        0.051850   0.762376
23        -0.136201       -0.562211   0.774349
24         0.073115       -0.795469  -0.581939
25        -0.199312        0.656489  -0.603517
26         0.035370        0.821718  -0.635835
27        -0.035519        0.235069   1.174271
28        -0.168793        2.210141  -0.767189
29        -0.178609        1.142457  -0.858134
30        -0.258074       -0.205629  -0.990357
31        -0.276958        1.130554  -1.014419
32        -0.226949        0.283924  -1.362450
33        -0.401129       -0.659324   0.029817
34        -0.600682        1.310535  -0.001879
35        -0.609750       -1.308658  -0.045493
36        -0.991570        0.205925  -0.081763
37        -0.652532       -2.525994  -0.115608
38        -1.177178       -1.997270  -0.212785
39        -0.773820       -1.383122  -0.297583
40        -0.989577       -0.100900  -0.315786
41        -1.008534       -1.320796  -0.384552
42        -1.102106       -0.906938  -0.520596
43        -1.281134        0.217682  -1.449605
44        -1.134305        1.206419  -1.509074
45        -1.600350        0.101254  -1.727400
46        -1.593413       -0.199322   0.711122
47        -1.622362        0.507722  -1.743127
48        -1.610433       -2.509409  -1.743127
49        -1.622362       -0.157226  -1.369985

In [32]:
df.drop(['Marketing Spend','Administration','Transport'], axis= 1, inplace= True, errors= 'ignore')
df

       Profit  Area_Dhaka  Area_Rangpur
0   192261.83           1             0
1   191792.06           0             0
2   191050.39           0             1
3   182901.99           1             0
4   166187.94           0             1
5   156991.12           1             0
6   156122.51           0             0
7   155752.60           0             1
8   152211.77           1             0
9   149759.96           0             0
10  146121.95           0             1
11  144259.40           0             0
12  141585.52           0             1
13  134307.35           0             0
14  132602.65           0             1
15  129917.04           1             0
16  126992.93           0             0
17  125370.37           1             0
18  124266.90           0             1
19  122776.86           1             0
20  118474.03           0             0
21  111313.02           1             0
22  110352.25           0             1
23  108733.99           0             1
24  108552.04           1             0
25  107404.34           0             0
26  105733.54           0             1
27  105008.31           1             0
28  103282.38           0             1
29  101004.64           1             0
30   99937.59           0             1
31   97483.56           1             0
32   97427.84           0             0
33   96778.92           0             1
34   96712.80           0             0
35   96479.51           1             0
36   90708.19           0             1
37   89949.14           0             0
38   81229.06           1             0
39   81005.76           0             0
40   78239.91           0             0
41   77798.83           0             1
42   71498.49           0             0
43   69758.98           1             0
44   65200.33           0             0
45   64926.08           1             0
46   49490.75           0             1
47   42559.73           0             0
48   35673.41           1             0
49   14681.40           0             0

In [33]:
Processed_df = pd.concat([scaled_df, df], axis= 1)
Processed_df

,Marketing Spend,Administration,Transport,Profit,Area_Dhaka,Area_Rangpur
0,0.897913,0.560753,2.153943,192261.83,1,0
1,1.955860,1.082807,1.923600,191792.06,0,0
2,1.754364,-0.728257,1.626528,191050.39,0,1
3,1.554784,-0.096365,1.422210,182901.99,1,0
4,1.504937,-1.079919,1.281528,166187.94,0,1
5,1.279800,-0.776239,1.254210,156991.12,1,0
6,1.340066,0.932147,-0.688150,156122.51,0,0
7,1.245057,0.871980,0.932186,155752.60,0,1
8,1.030369,0.986952,0.830887,152211.77,1,0
9,1.091819,-0.456640,0.776107,149759.96,0,0
10,0.620398,-0.387599,0.149807,146121.95,0,1
11,0.593085,-1.065540,0.319834,144259.40,0,0
12,0.443260,0.215449,0.320617,141585.52,0,1
13,0.402078,0.510179,0.343957,134307.35,0,0
14,1.017181,1.269199,0.375742,132602.65,0,1
15,2.016411,0.045868,0.419219,129917.04,1,0
16,0.094441,0.009118,0.440446,126992.93,0,0
17,0.460720,0.855666,0.591017,125370.37,1,0
18,0.396725,-0.258465,0.692992,124266.90,0,1
19,0.279442,1.159837,-1.743127,122776.86,1,0
20,0.055726,-0.269588,0.723926,118474.03,0,0
21,0.102724,1.169186,0.732788,111313.02,1,0
22,0.006007,0.051850,0.762376,110352.25,0,1
23,-0.136201,-0.562211,0.774349,108733.99,0,1
24,0.073115,-0.795469,-0.581939,108552.04,1,0
25,-0.199312,0.656489,-0.603517,107404.34,0,0
26,0.035370,0.821718,-0.635835,105733.54,0,1
27,-0.035519,0.235069,1.174271,105008.31,1,0
28,-0.168793,2.210141,-0.767189,103282.38,0,1
29,-0.178609,1.142457,-0.858134,101004.64,1,0
30,-0.258074,-0.205629,-0.990357,99937.59,0,1
31,-0.276958,1.130554,-1.014419,97483.56,1,0
32,-0.226949,0.283924,-1.362450,97427.84,0,0
33,-0.401129,-0.659324,0.029817,96778.92,0,1
34,-0.600682,1.310535,-0.001879,96712.80,0,0
35,-0.609750,-1.308658,-0.045493,96479.51,1,0
36,-0.991570,0.205925,-0.081763,90708.19,0,1
37,-0.652532,-2.525994,-0.115608,89949.14,0,0
38,-1.177178,-1.997270,-0.212785,81229.06,1,0
39,-0.773820,-1.383122,-0.297583,81005.76,0,0
40,-0.989577,-0.100900,-0.315786,78239.91,0,0
41,-1.008534,-1.320796,-0.384552,77798.83,0,1
42,-1.102106,-0.906938,-0.520596,71498.49,0,0
43,-1.281134,0.217682,-1.449605,69758.98,1,0
44,-1.134305,1.206419,-1.509074,65200.33,0,0
45,-1.600350,0.101254,-1.727400,64926.08,1,0
46,-1.593413,-0.199322,0.711122,49490.75,0,1
47,-1.622362,0.507722,-1.743127,42559.73,0,0
48,-1.610433,-2.509409,-1.743127,35673.41,1,0
49,-1.622362,-0.157226,-1.369985,14681.40,0,0

##  **Applying train_test_solit**

In [34]:
X = Processed_df.drop('Profit', axis= 1)
y = Processed_df.Profit

In [35]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [36]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((40, 5), (10, 5), (40,), (10,))

## Training the Linear Regression Model

In [37]:
lr = LinearRegression()
lr.fit( X_train, y_train)
y_pred = lr.predict(X_test)
y_pred

array([127493.87822504,  84215.82430049,  91461.57151594,  43319.81525396,
       131483.05795156,  42051.47018348, 104559.9957418 ,  98910.5641263 ,
        89643.08462153, 100498.23170594])

## **Evaluatuion**

In [42]:
R2 = r2_score(y_test, y_pred)
R2

0.8389824679944405

In [43]:
MSE = mean_squared_error(y_test, y_pred)
MSE

130390721.14429131

In [46]:
RMSE = root_mean_squared_error(y_test, y_pred)
RMSE

11418.875651494385

In [44]:
MAE = mean_absolute_error(y_test, y_pred)
MAE

9232.727124502395

In [48]:
y_mean = y_test.mean()
y_mean

np.float64(97456.31399999998)

In [50]:
mae_percentage = (MAE / y_mean) * 100
rmse_percentage = (RMSE / y_mean) * 100

In [52]:
print(f"Mean of Targeted column: {y_mean:.2f}")
print(f"MAE and Mean Percantage: {mae_percentage:.2f}%")
print(f"RMSE and Mean Percantage: {rmse_percentage:.2f}%")

Mean of Targeted column: 97456.31
MAE and Mean Percantage: 9.47%
RMSE and Mean Percantage: 11.72%